import { test, expect } from '@playwright/test'

const host = { id: 'fixture-host', name: 'Test host', host: 'example.com', port: 22, username: 'tester', startPath: '/remote', auth: 'password', privateKeyPath: '' }
const remote = { path: '/remote', parent: '/', home: '/remote', entries: [{ name: 'remote.txt', path: '/remote/remote.txt', directory: false, symlink: false, size: 12, mode: 420, modified: '2026-10-06T05:00:00Z' }] }

test('save, edit, reload, and delete a private-key connection', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Connections/ }).click()
  await page.getByRole('button', { name: '+ Add connection', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Saved host')
  await page.getByLabel('Host', { exact: true }).fill('example.com')
  await page.getByLabel('Port', { exact: true }).fill('2222')
  await page.getByLabel('Username', { exact: true }).fill('tester')
  await page.getByLabel('Start path', { exact: true }).fill('/srv')
  await page.getByLabel('Authentication', { exact: true }).selectOption('privateKey')
  await page.getByLabel('Private-key file', { exact: true }).fill('/tmp/scp-client-fixture-key')
  await page.getByRole('button', { name: 'Save connection', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Saved host', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.reload()
  await page.getByRole('button', { name: /Connections/ }).click()
  await expect(page.getByRole('heading', { name: 'Saved host', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit Saved host', exact: true }).click()
  await expect(page.getByLabel('Key passphrase (if encrypted)', { exact: true })).toHaveValue('')
  await page.getByLabel('Name', { exact: true }).fill('Renamed host')
  await page.getByRole('button', { name: 'Save connection', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Renamed host', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Renamed host', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Renamed host', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Renamed host', exact: true }).click()
  await page.getByRole('button', { name: 'Delete connection', exact: true }).click()
  await expect(page.getByText('No saved connections', { exact: true })).toBeVisible()
})

test('trust connects only the active pane and disconnect restores its local path', async ({ page }) => {
  const requests: Record<string, unknown>[] = []
  await page.route('**/api/connections', route => route.fulfill({ json: [host] }))
  await page.route('**/api/sessions', async route => {
    const body = route.request().postDataJSON()
    requests.push(body)
    if (!body.trustFingerprint) await route.fulfill({ status: 412, json: { code: 'unknown_host_key', message: 'Verify host', keyType: 'ssh-ed25519', fingerprint: 'SHA256:verified-host-key' } })
    else await route.fulfill({ status: 201, json: { ...remote, sessionId: 'remote-session', connectionId: host.id, name: host.name } })
  })
  await page.route('**/api/sessions/remote-session', route => route.fulfill({ status: 204 }))
  await page.route('**/api/list?kind=sftp**', async route => {
    const directory = new URL(route.request().url()).searchParams.get('path')
    await route.fulfill({ json: directory === '/' ? { ...remote, path: '/', parent: '/', entries: [{ ...remote.entries[0], name: 'remote', path: '/remote', directory: true }] } : remote })
  })
  await page.goto('/')
  const leftPath = page.getByRole('textbox', { name: 'Left directory path' })
  const rightPath = page.getByRole('textbox', { name: 'Right directory path' })
  await expect(leftPath).not.toHaveValue('')
  const localLeft = await leftPath.inputValue()
  const localRight = await rightPath.inputValue()
  await page.getByRole('button', { name: /Connections/ }).click()
  await page.getByRole('button', { name: 'Connect Test host', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Trust this host?', exact: true })).toBeVisible()
  await expect(page.getByText('SHA256:verified-host-key', { exact: true })).toBeVisible()
  await expect(leftPath).toHaveValue(localLeft)
  await page.getByRole('button', { name: 'Trust and connect', exact: true }).click()
  await expect(leftPath).toHaveValue('/remote')
  await expect(rightPath).toHaveValue(localRight)
  const left = page.getByRole('region', { name: 'Left file pane' })
  await expect(left.getByText('remote.txt', { exact: true })).toBeVisible()
  await expect(left.getByText('Test host', { exact: true })).toBeVisible()
  await left.getByRole('button', { name: '↑ Parent', exact: true }).click()
  await expect(leftPath).toHaveValue('/')
  await left.getByRole('button', { name: '⌂ Home', exact: true }).click()
  await expect(leftPath).toHaveValue('/remote')
  await left.getByRole('button', { name: 'Disconnect', exact: true }).click()
  await expect(leftPath).toHaveValue(localLeft)
  await expect(rightPath).toHaveValue(localRight)
  await expect(left.getByText('This Mac', { exact: true })).toBeVisible()
  expect(requests[1].trustFingerprint).toBe('SHA256:verified-host-key')
})

test('wrong password and changed host key leave the pane local', async ({ page }) => {
  await page.route('**/api/connections', route => route.fulfill({ json: [host] }))
  let attempts = 0
  await page.route('**/api/sessions', async route => {
    attempts++
    await route.fulfill({ status: attempts === 1 ? 401 : 409, json: attempts === 1 ? { code: 'auth_failed', message: 'SSH authentication failed' } : { code: 'host_key_changed', message: 'The host key no longer matches the trusted key.' } })
  })
  await page.goto('/')
  const path = page.getByRole('textbox', { name: 'Left directory path' })
  await expect(path).not.toHaveValue('')
  const local = await path.inputValue()
  await page.getByRole('button', { name: /Connections/ }).click()
  await page.getByRole('button', { name: 'Connect Test host', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('SSH authentication failed')
  await expect(path).toHaveValue(local)
  await page.getByRole('button', { name: 'Connect Test host', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('The host key no longer matches the trusted key.')
  await expect(page.getByRole('button', { name: 'Trust and connect' })).toHaveCount(0)
  await expect(path).toHaveValue(local)
})

test('encrypted key prompts for a passphrase and offers Keychain saving', async ({ page }) => {
  await page.route('**/api/connections', route => route.fulfill({ json: [{ ...host, auth: 'privateKey', privateKeyPath: '/tmp/encrypted-key' }] }))
  const logins: Record<string, unknown>[] = []
  await page.route('**/api/sessions', async route => {
    const body = route.request().postDataJSON()
    logins.push(body)
    if (!body.secret) await route.fulfill({ status: 428, json: { code: 'passphrase_required', message: 'This private key is encrypted.' } })
    else await route.fulfill({ status: 201, json: { ...remote, sessionId: 'encrypted-session', connectionId: host.id, name: host.name } })
  })
  await page.goto('/')
  await page.getByRole('button', { name: /Connections/ }).click()
  await page.getByRole('button', { name: 'Connect Test host', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Unlock connection', exact: true })).toBeVisible()
  await page.getByLabel('Private-key passphrase', { exact: true }).fill('fixture-passphrase')
  await expect(page.getByLabel('Save in macOS Keychain', { exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Connect', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Left directory path' })).toHaveValue('/remote')
  expect(logins[1].secret).toBe('fixture-passphrase')
  expect(logins[1].saveSecret).toBe(true)
})

test('disconnect clears remote rows even if the old local directory is gone', async ({ page }) => {
  await page.route('**/api/connections', route => route.fulfill({ json: [host] }))
  await page.route('**/api/sessions', route => route.fulfill({ status: 201, json: { ...remote, sessionId: 'removed-local-session', connectionId: host.id, name: host.name } }))
  await page.route('**/api/sessions/removed-local-session', route => route.fulfill({ status: 204 }))
  await page.goto('/')
  const path = page.getByRole('textbox', { name: 'Left directory path' })
  await expect(path).not.toHaveValue('')
  const original = await path.inputValue()
  await page.getByRole('button', { name: /Connections/ }).click()
  await page.getByRole('button', { name: 'Connect Test host', exact: true }).click()
  await expect(path).toHaveValue('/remote')
  await page.route('**/api/list?kind=local**', route => route.fulfill({ status: 400, json: { code: 'invalid_path', message: 'Local directory no longer exists' } }))
  const left = page.getByRole('region', { name: 'Left file pane' })
  await left.getByRole('button', { name: 'Disconnect', exact: true }).click()
  await expect(path).toHaveValue(original)
  await expect(left.getByRole('alert')).toHaveText('Local directory no longer exists')
  await expect(left.getByText('remote.txt', { exact: true })).toHaveCount(0)
  await expect(left.getByText('This Mac', { exact: true })).toBeVisible()
})
